name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [16, 18, 20]
                os: [ubuntu-latest, windows-latest, macos-latest]
                include:
                    - node-version: 16
                      os: ubuntu-latest
                    - node-version: 18
                      os: windows-latest
                    - node-version: 20
                      os: macos-latest
                exclude:
                    - node-version: 16
                      os: windows-latest
                    - node-version: 18
                      os: macos-latest
                    - node-version: 20
                      os: ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Run build
              run: npm run build