name: Reusable Deploy
on: 
 workflow_call:
    inputs:
        artifact_name: 
            description: 'Name of the artifact to deploy'
            required: true
            type: string
            default: dist
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact_name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploying..."